/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthView: typeof import('./src/views/AuthView.vue')['default']
    CreateItemModal: typeof import('./src/components/CreateItemModal.vue')['default']
    DeleteConfirmModal: typeof import('./src/components/DeleteConfirmModal.vue')['default']
    GVNotes: typeof import('./src/views/GVNotes.vue')['default']
    NavPanel: typeof import('./src/components/NavPanel.vue')['default']
    NavPanelHeader: typeof import('./src/components/NavPanelHeader.vue')['default']
    NoteEditor: typeof import('./src/components/NoteEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
