// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CreateNote(arg1:dto.CreateNoteRequest):Promise<dto.NoteDetail>;

export function CreateNotebook(arg1:dto.CreateNotebookRequest):Promise<dto.NotebookDetail>;

export function DeleteImage(arg1:string):Promise<void>;

export function DeleteNote(arg1:string):Promise<void>;

export function DeleteNotebook(arg1:string):Promise<void>;

export function GetAuthStatus():Promise<any>;

export function GetImage(arg1:string):Promise<dto.ImageItem>;

export function GetImagePath(arg1:string):Promise<string>;

export function GetImageServerURL():Promise<string>;

export function GetNote(arg1:string):Promise<dto.NoteDetail>;

export function GetNotebook(arg1:string):Promise<dto.NotebookDetail>;

export function ListImagesByNote(arg1:string):Promise<Array<dto.ImageItem>>;

export function ListNotebooks(arg1:string):Promise<Array<dto.NotebookListItem>>;

export function ListNotes(arg1:string):Promise<Array<dto.NoteListItem>>;

export function SaveImage(arg1:string,arg2:string,arg3:Array<number>):Promise<dto.ImageItem>;

export function SetPassword(arg1:string):Promise<any>;

export function UpdateNoteContent(arg1:string,arg2:dto.UpdateNoteContentRequest):Promise<dto.NoteDetail>;

export function UpdateNotePosition(arg1:string,arg2:dto.UpdatePositionRequest):Promise<void>;

export function UpdateNoteTitle(arg1:string,arg2:dto.UpdateNoteTitleRequest):Promise<dto.NoteDetail>;

export function UpdateNotebookPosition(arg1:string,arg2:dto.UpdatePositionRequest):Promise<void>;

export function UpdateNotebookTitle(arg1:string,arg2:dto.UpdateNotebookTitleRequest):Promise<dto.NotebookDetail>;

export function VerifyPassword(arg1:string):Promise<any>;
