// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}

export function CreateNotebook(arg1) {
  return window['go']['main']['App']['CreateNotebook'](arg1);
}

export function DeleteImage(arg1) {
  return window['go']['main']['App']['DeleteImage'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteNotebook(arg1) {
  return window['go']['main']['App']['DeleteNotebook'](arg1);
}

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function GetImage(arg1) {
  return window['go']['main']['App']['GetImage'](arg1);
}

export function GetImagePath(arg1) {
  return window['go']['main']['App']['GetImagePath'](arg1);
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function GetNotebook(arg1) {
  return window['go']['main']['App']['GetNotebook'](arg1);
}

export function ListImagesByNote(arg1) {
  return window['go']['main']['App']['ListImagesByNote'](arg1);
}

export function ListNotebooks(arg1) {
  return window['go']['main']['App']['ListNotebooks'](arg1);
}

export function ListNotes(arg1) {
  return window['go']['main']['App']['ListNotes'](arg1);
}

export function SaveImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2, arg3);
}

export function SetPassword(arg1) {
  return window['go']['main']['App']['SetPassword'](arg1);
}

export function UpdateNoteContent(arg1, arg2) {
  return window['go']['main']['App']['UpdateNoteContent'](arg1, arg2);
}

export function UpdateNotePosition(arg1, arg2) {
  return window['go']['main']['App']['UpdateNotePosition'](arg1, arg2);
}

export function UpdateNoteTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateNoteTitle'](arg1, arg2);
}

export function UpdateNotebookPosition(arg1, arg2) {
  return window['go']['main']['App']['UpdateNotebookPosition'](arg1, arg2);
}

export function UpdateNotebookTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateNotebookTitle'](arg1, arg2);
}

export function VerifyPassword(arg1) {
  return window['go']['main']['App']['VerifyPassword'](arg1);
}
